#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Enable caching packages for all repositories
zypper modifyrepo --all --keep-packages
zypper addrepo "dir:/mnt/repos/install" "SLES16-FULL"
zypper refresh

# Remove python to get rid of anything extra we don't want
zypper remove -y --force-resolution  "python3*" || true
zypper remove -y jeos-firstboot
zypper install -y "python313"
zypper install -y "python313-devel"

# Print python binaries for debugging
echo "Python binaries in /usr/bin before symlinking:"
ls -la /usr/bin | grep "python"

# ln -s "/usr/bin/python3.13" "/usr/bin/python3"
ln -s "/usr/bin/python3.13" "/usr/bin/python"

echo "python3 version: $(python3 --version 2>&1 || true)"
echo "python version: $(python --version 2>&1 || true)"
