#!/bin/bash
# The base image created by kiwi does not contain an initrd so create one
# here.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Specify the filesystems with --filsystems to include the right tools for the
# root filesystem that will actually be used for the final image. This is
# likely something different than what the chroot is currently on (which might
# currently be a tmpfs even).
dracut --force --regenerate-all \
	--filesystems "${DIB_ROOT_FSTYPE}"
