#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# This file should be the last one to execute. Hence delete zypper/rpm and
# their libraries here, deleting them before would break the installation.
rm -rf /usr/lib/rpm \
    /usr/lib/zypp \
    /usr/lib/zypper \
    /usr/lib64/zypp* \
    /usr/lib64/libzypp* \
    /usr/lib64/librpm* \
    /etc/zypp \
    /usr/bin/suseconnect \
    /usr/bin/zypper \
    /usr/lib/sysimage 
