#!/bin/bash

if [[ ${DIB_DEBUG_TRACE:-0} -gt 0 ]]; then
    set -x
fi
set -eu
set -o pipefail

VENV=/opt/ironic-python-agent
source "${VENV}/bin/activate"
export PBR_VERSION="1.0"
python -m pip install --upgrade pip
python -m pip install "setuptools>=40.8.0"

IFS=',' read -r -a plugins <<< "${DIB_IPA_PLUGINS}"
for plugin in "${plugins[@]}"; do
    echo "INSTALLING PLUGIN: ${plugin}"
    python -m pip install --verbose "/opt/${plugin}"
done
deactivate
