# DISTOR_NAME is opensuse in order to levarage the functionality of pkg-map and svc-map DIB tools
export DISTRO_NAME="opensuse"
export DIB_INIT_SYSTEM="systemd"
export DIB_OFFLINE="true"
export DIB_SLES_OFFLINE_TARGET_DIR="/$HOME/sles_images"
export DIB_SLES_ISO_REPO_FILE="${DIB_SLES_ISO_REPO_FILE:-SLE-15-SP7-Full-x86_64-GM-Media1.iso}"
export DIB_SLES_RELEASE="${DIB_SLES_RELEASE:-SLE-15}"
export DIB_SLES_SERVICE_PACK="${DIB_SLES_SERVICE_PACK:-SP7}"
export DIB_SLES_INSTALL_TYPE="${DIB_SLES_INSTALL_TYPE:-Minimal-VM}"
export DIB_SLES_IMAGE_TARGET_PLATFORM="${DIB_SLES_IMAGE_TARGET_PLATFORM:-OpenStack-Cloud-GM}"
export DIB_SLES_BUILD_NUM="${DIB_SLES_BUILD_NUM:-202204}"
